### ISSUE TITLE
Cleanup old cached files

### ISSUE THREAD

**Issue by anatol** [anatol/pacoloco#3]
Currently `pacoloco` does not do anything with the old cached files. But older files have less chance to be reused so we need to purge them to save some disk space.

A simple solution like having a config option `clean_after: 1m` should be fine.

**Comment by stevleibelt** [comment]
I would suggest setting the default to 3600 or even a bit more minutes.
From my habit, I am upgrade one machine today and would upgrade all others right a day after all is still fine.

Since I found a todo in your code that there can be issues if the same file is requested from multiple clients at the same time and pacoloco tries to download this one file multiple times, I would to increase the chance this can happen by setting the default cleanup time that low.

**Comment by anatol** [comment]
I was thinking about keeping the files for period ~ 1 month by default. I just realized that `clean_after: 1m` is ambiguous. It can be read as 1 minute, that is way low value.

**Comment by stevleibelt** [comment]
@anatol I needed, I stepped into this trap :-D.
`1 month` is indeed a very good time period. :+1:
