### ISSUE TITLE
Race condition when multiple clients request the same uncached file while still downloading

### ISSUE THREAD

**Issue by maxmitti** [anatol/pacoloco#30]
Under certain circumstances, pacoloco replies only a partial file to clients.

For the sake of simplicity, assume there are 2 clients (clients `A` and `B`), and both request the file `foo.pkg`.
Assume further that `foo.pkg` is not cached yet and has to be downloaded by pacoloco first.
Now imagine `A` requests `foo.pkg` first. pacoloco will start downloading the file from the server, save it in the cache and let `A` wait on the download to finish (ignoring further details here).
While it is still downloading `foo.pkg`, `B` also requests `foo.pkg`.
One would expect pacoloco to make `B` also wait on the completion of the download.
Actually, it will send the partially downloaded to `B` immediately as if it was the whole file.
In the end this will lead to pacman complaining about the file being corrupt.

This actually happened to me with some bigger package when I updated two machines simultaneously.

It is not a big issue, because pacman asks to delete the file anyway and on the next try it will probably be downloaded completely already. But it is confusing at least. Especially when it happens for the first time.

Seems like there is only some internal synchronization missing.

**Comment by Focshole** [comment]
I think the issue is there:
https://github.com/anatol/pacoloco/blob/7b8803ca68636f274fd4deafc7b8c1386d154c05/pacoloco.go#L267
The check is:
```go
		stat, err = os.Stat(filePath)
		noFile = err != nil
		requestFromServer = noFile || forceCheckAtServer(fileName)```
Which clearly does not check if it is being downloaded (the file is there, so `noFile` becomes `true`,  `requestFromServer` becomes `false` (force checking can be true only for db files and alike).

Checking if it is one of those which is being downloaded should detect that situation.

Now, the complex part may be how to solve it. I have 2 ideas:
1) Bad/lazy approach: simply create a new download just for that (it would probably have a file name collision), which makes pacoloco not so useful for not cached yet packages.
2) Good/complex approach: stream the partially cached file and ensure that the whole file gets served even if the first client  drops its connection.

**Comment by maxmitti** [comment]
Yes, that explains perfectly what is happening.

I think the lazy approach should not even be an option.
It would be even slower than the current case, when thinking of slow download speeds.

The second approach seems good to me.
Perhaps downloading can be made independent of client connections, if it is not yet.

**Comment by Focshole** [comment]
Fully agree on that, I do not see any easy solution for that right now, because this issue's solution is similar to https://github.com/anatol/pacoloco/issues/7 . The bad solution can be implemented as a temporary fix while dealing with the other one, which is the hard part (I'm not much into networking in go)
