### ISSUE TITLE
[feature request] add timestamps to log and support blackarch and aur repos

### ISSUE THREAD

**Issue by cocoonkid** [anatol/pacoloco#56]
[feature request] add timestamps to log and support blackarch and aur repos

I tried pacoloco and it is great but it does not cache my aur or blackarch packages even though I have added the repo urls to the config. The config is being read and work.

Thanks for your help!

**Comment by Focshole** [comment]
Do you see any errors in your logs? 
You cannot cache aur packages because they are not supplied as packages from a mirror, unless you set up a local mirror which builds your packages or you use an [unofficial mirror](https://wiki.archlinux.org/title/unofficial_user_repositories).

I'd expect blackarch packages to be cached. Are you sure that they are being fetched through pacoloco?

**Comment by Focshole** [comment]
I think this is closed and fixed now!
