### ISSUE TITLE
Add support for partial transfers

### ISSUE THREAD

**Issue by anatol** [anatol/pacoloco#7]
`pacoloco` needs to handle `Accept-Ranges` HTTP header to let client complete partially downloaded files.

**Comment by Focshole** [comment]
Dunno if [this](https://stackoverflow.com/questions/36540610/how-to-serve-http-partial-content-with-go) could help, maybe it could be a basis to start, knowing that right now `io.Copy` is being used to serve to the client and the file

**Comment by Jabbermuggel** [comment]
I believe I have a working solution for this and #30. I implemented an alternative download mechanism which separates the download and serving to clients. I used an existing download library called grab, which just saves the files directly to disk (and has a few other features like rate limiting one could implement in the future, although a normal get and write with io would probably work as well). I wrote a Wrapper around a file-type object implementing the io.ReadSeeker-interface, which knows what size the file will be once it has finished downloading and delays read processes trying to access data that isn't there yet. With the ReadSeeker-interface I could use http.ServeContent in favor of io.Copy, which has the advantages of supporting byte-ranges, automatically setting headers and not throwing broken pipe errors if the client disconnects. Since the processes serving files to the clients is separated from the actual download there is no problem in multiple clients getting the same file, solving #30. The behavior is as you'd expect, any new clients catching up and then downloading at whatever rate the server is getting the file from the remote mirror.

I have put a proof of concept [here](https://github.com/Jabbermuggel/go-mirror-server); I used a local file server with download rate limits and multiple curl calls for testing. I heavily modified the structure of pacoloco.go, so if this is a good approach it will hopefully be relatively painless to implement it here.

**Comment by anatol** [comment]
Hi @Jabbermuggel 

This is fantastic news. These 2 issues are probably the top bugs that pacoloco has now and it would be great to get them fixed.

> I wrote a Wrapper around a file-type object implementing the io.ReadSeeker-interface, which knows what size the file will be once it has finished downloading and delays read processes trying to access data that isn't there yet. With the ReadSeeker-interface I could use http.ServeContent in favor of io.Copy, which has the advantages of supporting byte-ranges, automatically setting headers and not throwing broken pipe errors if the client disconnects. Since the processes serving files to the clients is separated from the actual download there is no problem in multiple clients getting the same file, solving https://github.com/anatol/pacoloco/issues/30. The behavior is as you'd expect, any new clients catching up and then downloading at whatever rate the server is getting the file from the remote mirror.

Just to clarify, will it handle the situation when multiple pacoloco clients try to download the same file? i.e. client A starts downloading a file, 10 seconds later client B asks for the same file. Does client B receive data for the partially downloaded file right away? Or client B will be blocked till the file is fully downloaded and only then it start pulling the data?

> I heavily modified the structure of pacoloco.go, so if this is a good approach it will hopefully be relatively painless to implement it here.

I fully support this idea. Once you have a PR I'll be glad to review and merge it.

**Comment by Jabbermuggel** [comment]
Yes, in your example client B will receive the part of the data that is already on the server right away at whatever speed the network supports (e. g. around 1G for a typical local network) and will then continue to receive data at the rate the pacoloco-server receives it from the internet.

I have started to implement my code into the pacoloco source and will create a PR once I have something workable.

**Comment by Focshole** [comment]
Ok, I just noticed something:
If the file is cached, pacoloco offers to serve range bytes
```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 119
Content-Type: application/pgp-signature
Last-Modified: Wed, 11 Jan 2023 20:52:29 GMT
Date: Thu, 02 Feb 2023 10:42:46 GMT
Connection: close```
Because the `http.ServeContent` is properly implemented for cached files. Given that we usually implement prefetching, I'd expect to reach a quite high cache hit most of the times after even a week of uptime.

What about forwarding those byte requests to the upstream mirror(s)? 
Overall this would be an amortized expense, we pay it once (as soon as pacoloco gets installed), then we won't pay for it again.
As we know [byte serving](https://stackoverflow.com/a/36543480/4746441) is not trivial at all. If we don't have the file, we should do some promises on what to give without even having it or knowing if it will be fully available. I have reviewed a bit @Jabbermuggel 's implementation, writing a custom file reader to receive a few parts is quite painful. Feel free to finish writing it in case!

**Comment by Jabbermuggel** [comment]
As I understand it you want to just forward byte requests and requests for currently downloading files to the public mirror, thus circumventing the problems the current implementation has with those cases. This would increase internet usage for those cases, but as they are probably rare it wouldn't be that bad.

I agree this is a decent workaround for the time being. My exams will be finished this week, so hopefully I'll find some time after that to properly implement the byte serving.

**Comment by Focshole** [comment]
Yes, exactly. The byte serving is required only in those situations and with this code refactoring is probably easier to introduce it :+1:
